### ISSUE TITLE
请教如何编译？

### ISSUE THREAD

**Issue by GenjiLuo** [ystcode/BlogHelper#17]
这个工具非常实用，希望能自己尝试添加一些发布源，请问如何编译、打包这个项目

**Comment by GenjiLuo** [comment]
我已经搭起了编译环境，编译过程中 npm install 时发生错误，错误信息如下：

npm ERR! Unexpected end of JSON input while parsing near '...":"~1.0.1","grunt-aut'

编译环境的要求，能指导一下吗！？

**Comment by ystcode** [comment]
网络问题，老兄还是去学习下npm吧！加油。一起做好这个开源项目！

**Comment by GenjiLuo** [comment]
是的，已经走到编译的最后了，又遇到了新问题。

我使用yarn install 来处理依赖包 和 编译，一切顺利，现在卡在

warning package.json: License should be a valid SPDX license expression
info No lockfile found.
warning blog-helper@1.0.16: License should be a valid SPDX license expression
[1/4] 🔍  Resolving packages...
warning jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[3/3] ⠂ electron
[2/3] ⠂ ejs
[-/3] ⠂ waiting...

**Comment by ystcode** [comment]
使用cnpm吧！
