### ISSUE TITLE
能支持Linux吗?

### ISSUE THREAD

**Issue by 2293736867** [ystcode/BlogHelper#20]
没啥,希望开发Linux版.

**Comment by ystcode** [comment]
本应用可编译为win、mac、linux等平台，不过linux需要自行编译。

**Comment by 2293736867** [comment]
ok，谢谢大佬。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"薛勤"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 中午12:02
收件人:&nbsp;"ystcode/BlogHelper"<BlogHelper@noreply.github.com&gt;;
抄送:&nbsp;"氷泠"<2293736867@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ystcode/BlogHelper] 能支持Linux吗? (#20)





 
本应用可编译为win、mac、linux等平台，不过linux需要自行编译。
