### ISSUE TITLE
[Question] 请问在任务栏看不到logo是什么原因

### ISSUE THREAD

**Issue by deanwong** [ystcode/BlogHelper#23]
就是这么设计的么？有点奇妙
![image](https://user-images.githubusercontent.com/4144156/82008661-e722b780-969f-11ea-98a0-e428a32d0f74.png)
![image](https://user-images.githubusercontent.com/4144156/82008675-ef7af280-969f-11ea-88e0-4da0ae97c425.png)

**Comment by ystcode** [comment]
Logo是白色，背景透明，在我的Mac OS10.15是没问题的，不知道你的版本是多少

**Comment by ystcode** [comment]
![](https://imgkr.cn-bj.ufileos.com/e2f1ccaa-477d-4749-bdec-ec3edd577a08.png)
