### ISSUE TITLE
Manjora 打开失败

### ISSUE THREAD

**Issue by cunyu1943** [ystcode/BlogHelper#26]
- 弹窗信息如下：

```
**A JavaScript error occurred in the main process**
Uncaught Exception：
TypeError：cannot read property `hide` of undefined
at App.<anonymous>(/tmp/.mount_BlogHerK3jmr/-resources/app.asar/src/main.js:10:77)
at App.emit(events.js:208:15)

```

![](https://user-gold-cdn.xitu.io/2020/5/23/172420966a68e6b8?w=566&h=271&f=png&s=26410)

**Comment by ystcode** [comment]
系统，版本，是什么

**Comment by cunyu1943** [comment]
- Manjora：manjaro-xfce-20.0.1-200511（64-bit）
然后试了一下 Linux Mint：Linux Mint 19.3 "Tricia" - Cinnamon (64-bit)，出现同样的情况

**Comment by ystcode** [comment]
Linux版本bug已修复。请重新下载即可哦
