### ISSUE TITLE
Linux Mint 编译失败

### ISSUE THREAD

**Issue by cunyu1943** [ystcode/BlogHelper#27]
🌟你使用的操作系统是：
- Linux Mint
🌟你使用的软件版本号是：
- Linux Mint 19.3 Cinnamon
🌟请叙述你的问题：
- clone 后编译报错，报错信息如下：
![](https://user-gold-cdn.xitu.io/2020/5/25/172498fc342713c1?w=764&h=289&f=png&s=61820)

**Comment by ystcode** [comment]
首先是软件版本号写错了。

**Comment by ystcode** [comment]
该bug已在develop分之修复完成。
