### ISSUE TITLE
如图片标题含中文异常

### ISSUE THREAD

**Issue by 360linux** [ystcode/BlogHelper#34]
🌟你使用的操作系统是：win10专业版

🌟你使用的软件版本号是：1.0.22

🌟请叙述你的问题：如果md文件图片引用这里有中文，如'[中文][http://xxxx.jpg,]', 图片不会下载,且在md图片转img时也异常
<img width="701" alt="企业微信截图_20200630222700" src="https://user-images.githubusercontent.com/11537607/86138484-20649900-bb21-11ea-894f-90efede26d9f.png">

**Comment by ystcode** [comment]
在你的文章中真实的引用文字是什么样的？

**Comment by 360linux** [comment]
@ystcode   我的意思是在引用图片的md文件语法里，在中括号[ ]这里，如果里面写了中文，在使用 文章-网络图片下载 这个功能时，这张引用的图片不会下载到本地。

**Comment by ystcode** [comment]
我试过了，没有你说的这个问题。
另外，在提交bug的时候，出现异常的数据要粘贴过来，方便复现，不要只要口头描述。

**Comment by 360linux** [comment]
我刚下载了最新的1.0.23版本，正常使用了，感谢大佬 @ystcode
