### ISSUE TITLE
请输入标题

### ISSUE THREAD

**Issue by fly7632785** [ystcode/BlogHelper#35]
🌟你使用的操作系统是：mac 10.15.4

🌟你使用的软件版本号是：1.0.22

🌟请叙述你的问题：mac 10.15.4 打不开，第一次打开请求访问文件夹权限同意后，打不开，二次也打不开
<img width="420" alt="image" src="https://user-images.githubusercontent.com/10276266/86423971-d42d7a80-bd13-11ea-94d1-c32346a68e7e.png">
然后自己创建了文件夹和publish.log文件
再次打开，同级目录下生成了BlogHelper.json
但是 状态栏依旧没有程序运行，但是活动监视器可以看到是在运行的
![image](https://user-images.githubusercontent.com/10276266/86424104-2a022280-bd14-11ea-9ace-37756250b859.png)

**Comment by ystcode** [comment]
已解决，mac系统选择浅色模式时会看不对应用图标。会尽快修复此bug。
