### ISSUE TITLE
win10上传github图床检测不到剪贴板图片

### ISSUE THREAD

**Issue by BKHole** [ystcode/BlogHelper#37]
🌟你使用的操作系统是：win10家庭中文版

🌟你使用的软件版本号是：1.0.23

🌟请叙述你的问题：win10上传github图床检测不到剪贴板图片，本地/网络图片已copy

**Comment by ystcode** [comment]
打开图片后复制图片，不要在文件夹复制图片文件，这两个操作不是一样的。
