### ISSUE TITLE
点击下载最新版本的1.0.24写作助手下载链接跳转到的是简单写作下载

### ISSUE THREAD

**Issue by lemonchann** [ystcode/BlogHelper#42]
1. 你使用的操作系统是：win10

2. 你使用的本软件版本号是：1.0.20

3. 请详细叙述你的问题：点击下载最新版本的1.0.24写作助手下载链接跳转到的是简单写作下载

4. 用于问题复现的数据：点击下载最新版本的1.0.24写作助手下载链接跳转到的是简单写作下载http://disk.ystblog.com/home.html;jsessionid=432854BEB3C7DBBA184B9AAFD3F7A63D

**Comment by ystcode** [comment]
找到网盘页面的根目录就有了

**Comment by lemonchann** [comment]
tks! 建议下载链接指向网盘根目录。

**Comment by ystcode** [comment]
本来就是默认指向的根目录。
只是因为你之前跳转过，本地缓存了而已。
